name: flutter_launcher_icons
description: Generate ios/android launcher icons for flutter
version: 0.2.0
homepage: https://github.com/franzsilva/flutter_launcher_icons
authors: 
- Franz Silva <franzsilva@gmail.com>
- Mark O'Sullivan <mos182@hotmail.co.uk>

dependencies: 
  image: "^1.1.29"
  dart_config: "^0.5.0"
  
environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
