name: flutter_launcher_icons
description: Generate ios/android launcher icons for flutter
version: 0.0.5
homepage: https://github.com/franzsilva/flutter_launcher_icons
author: Franz Silva <franzsilva@gmail.com>

dependencies: 
  image: "^1.1.29"
  dart_config: "^0.5.0"
  
environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
