name: flutter_launcher_icons
description: A package developed to simplify the task of updating your Flutter app's launcher icon. Fully flexible, allowing you to choose what platform you wish to update the launcher icon for and if you want, the option to keep your old launcher icon in case you want to revert back sometime in the future.
version: 0.2.2
homepage: https://github.com/franzsilva/flutter_launcher_icons
authors: 
- Franz Silva <franzsilva@gmail.com>
- Mark O'Sullivan <mos182@hotmail.co.uk>
- Aleksandr Krotov <san.crot@yandex.ru>

dependencies: 
  image: "^1.1.29"
  dart_config: "^0.5.0"
  
environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
